// Generated by Selenium IDE
const { Builder, By, Key, until, Capabilities } = require('selenium-webdriver')
const assert = require('assert')

describe('imdb-wandavision', function() {
  this.timeout(60000)
  let driver
  let vars
  let capabilities = new Capabilities().setBrowserName("firefox");
  before(async function() {
    driver = await new Builder()
        .usingServer("http://172.21.0.1:4444/wd/hub")
        .withCapabilities(capabilities)
        .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('imdb-wandavision', async function() {

    await driver.get("https://www.imdb.com//")
    await driver.findElement(By.id("suggestion-search")).sendKeys("wandavision")
    await driver.wait(() => imdb-wandavision(), 15000);
    await driver.findElement(By.css(".\\_2mXTyZmtWnrwCBj9tuEhuK .\\_2NPnhnjxKTlB8HDsb7RtwX")).click()
    await driver.findElement(By.css(".bp_content")).click()
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
